apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment
  labels:
    app: webapp
spec:
  selector:
    matchLabels:
      app: webapp
  replicas: 3
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        app: webapp
    spec:
      terminationGracePeriodSeconds: 1
      containers:
      - name: webapp-container
        image: maryamtaer/myapp:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080